// داده‌های Mock تورها؛ تاریخ‌ها نسبت به امروز ساخته می‌شوند تا همیشه «پیش‌رو» باشند.
import { addDays, toISO, withDuration } from './logic'
import type { Tour } from './types'

const FOOD = 'وعده‌های غذایی'
const common = { excluded_items: ['هزینه‌های شخصی', 'بیمهٔ تکمیلی'], enabled: true, status: 'upcoming' as const }

export function seedTours(now: Date = new Date()): Tour[] {
  const d = (n: number) => toISO(addDays(now, n))
  const t = (x: Omit<Tour, 'duration' | 'image' | 'excluded_items' | 'enabled' | 'status'> & Partial<Tour>): Tour =>
    withDuration({ ...common, image: `/images/destinations/${x.destination_id}.svg`, duration: 'یک روزه', ...x })
  return [
    t({ id: 1, title: 'تور کویر مصر', destination_id: 11, destination_name: 'کویر مصر', scope: 'domestic', tour_type: 'کویر', description: 'دو روز شب‌مانی در دل شن‌زارها، آسمان پرستاره و غروب کویر با راهنمایی که مسیرها را می‌شناسد.', start_date: d(5), end_date: d(6), price: 3_800_000, budget: 'متوسط', capacity: 20, remaining_capacity: 7, meeting_point: 'تهران، میدان آزادی', difficulty: 'متوسط', companions: ['زوج', 'دوستان'], recommended_for: ['شب‌گردان کویر', 'عکاسان'], included_items: ['اقامت در کمپ', FOOD, 'راهنمای تور', 'ایاب‌وذهاب'], guide_name: 'مریم احمدی' }),
    t({ id: 2, title: 'تور پاییزی ماسوله', destination_id: 8, destination_name: 'ماسوله', scope: 'domestic', tour_type: 'جنگل', description: 'پیاده‌روی در جنگل‌های رنگی و کوچه‌های پلکانی ماسوله با توقف در اقامتگاه بوم‌گردی.', start_date: d(12), end_date: d(13), price: 2_200_000, budget: 'اقتصادی', capacity: 24, remaining_capacity: 11, meeting_point: 'تهران، ترمینال غرب', difficulty: 'آسان', companions: ['خانواده', 'زوج', 'دوستان'], recommended_for: ['دوستداران طبیعت', 'سفر خانوادگی'], included_items: ['اقامت', 'صبحانه', 'ایاب‌وذهاب'], guide_name: 'علی رضایی' }),
    t({ id: 3, title: 'تور چابهار', destination_id: 6, destination_name: 'چابهار', scope: 'domestic', tour_type: 'ساحل', description: 'پنج روز میان ساحل‌های دریای عمان و کوه‌های مینیاتوری، با زمان آزاد برای دریا.', start_date: d(24), end_date: d(28), price: 9_500_000, budget: 'متوسط', capacity: 16, remaining_capacity: 3, meeting_point: 'فرودگاه چابهار', difficulty: 'آسان', companions: ['زوج', 'دوستان', 'انفرادی'], recommended_for: ['دوستداران دریا', 'سفر طولانی'], included_items: ['اقامت', 'صبحانه', 'راهنما', 'قایق‌سواری'], guide_name: 'حسین کریمی' }),
    t({ id: 4, title: 'تور یزد و کویر', destination_id: 1, destination_name: 'یزد', scope: 'domestic', tour_type: 'فرهنگی', description: 'چهار روز گشت در بافت تاریخی یزد و یک شب‌مانی کویری؛ ترکیبی از فرهنگ و طبیعت.', start_date: d(40), end_date: d(43), price: 6_400_000, budget: 'متوسط', capacity: 18, remaining_capacity: 9, meeting_point: 'یزد، میدان امیرچخماق', difficulty: 'آسان', companions: ['خانواده', 'زوج', 'دوستان'], recommended_for: ['دوستداران معماری', 'عکاسان'], included_items: ['اقامت', FOOD, 'راهنمای تور', 'بلیت بناها'], guide_name: 'نرگس صادقی' }),
    t({ id: 5, title: 'تور استانبول', destination_id: 13, destination_name: 'استانبول', scope: 'international', tour_type: 'شهری', description: 'شش روز گردش در استانبول؛ از ایاصوفیه تا بازار بزرگ و سفر دریایی در بسفر.', start_date: d(85), end_date: d(90), price: 38_000_000, budget: 'لوکس', capacity: 14, remaining_capacity: 5, meeting_point: 'فرودگاه امام خمینی', difficulty: 'آسان', companions: ['خانواده', 'زوج', 'دوستان'], recommended_for: ['دوستداران تاریخ و خرید', 'سفر خانوادگی'], included_items: ['بلیت هواپیما', 'هتل', 'صبحانه', 'راهنما'], excluded_items: ['ویزا (در صورت نیاز)', 'هزینه‌های شخصی'], guide_name: 'سارا حسینی' }),
    t({ id: 6, title: 'تور تفلیس', destination_id: 14, destination_name: 'تفلیس', scope: 'international', tour_type: 'شهری', description: 'چهار روز در کوچه‌های سنگی تفلیس، گرمابه‌های گوگردی و کافه‌های رنگارنگ.', start_date: d(9), end_date: d(12), price: 24_000_000, budget: 'متوسط', capacity: 12, remaining_capacity: 0, meeting_point: 'فرودگاه امام خمینی', difficulty: 'آسان', companions: ['زوج', 'دوستان', 'انفرادی'], recommended_for: ['سفر اقتصادی', 'دوستداران شهر قدیمی'], included_items: ['بلیت هواپیما', 'هتل', 'صبحانه'], guide_name: 'رضا نوری' }),
    // تور پایان‌یافته؛ نباید در فهرست نمایش داده شود
    t({ id: 7, title: 'تور گذشتهٔ کاشان', destination_id: 4, destination_name: 'کاشان', scope: 'domestic', tour_type: 'فرهنگی', description: 'تور یک‌روزهٔ کاشان که برگزار شده است.', start_date: d(-10), end_date: d(-10), price: 1_200_000, budget: 'اقتصادی', capacity: 20, remaining_capacity: 0, meeting_point: 'تهران، میدان آزادی', difficulty: 'آسان', companions: ['خانواده'], recommended_for: ['سفر کوتاه'], included_items: ['ایاب‌وذهاب'], guide_name: 'علی رضایی', status: 'finished' }),
  ]
}
